#! /bin/sh

bspc config border_width        5
bspc config window_gap         12

bspc config split_ratio         0.5
bspc config borderless_monocle  false
bspc config gapless_monocle     false

bspc monitor -d 1 2 3 4 5

bspc rule -a Gimp desktop=^5 follow=on floating=on
bspc rule -a Firefox desktop=^2
bspc rule -a vlc floating=on
bspc rule -a Screenkey manage=off
bspc rule -a feh floating=on
bspc rule -a conky floating=on manage=off

bspc config focused_border_color "#FFFFFF"
bspc config normal_border_color  "#BBBBBB"
#bspc config top_padding 24